#!/usr/bin/env python3
"""
release_report.py

Renders one release record (release_record.py) plus its chain-of-custody
status (verify_chain.py) as a single, self-contained Markdown report --
something to actually hand to a non-technical reader (an auditor, a
lawyer, a hiring manager) as evidence, rather than a JSON file and a
terminal command they'd have to run themselves.

Run with: python3 release_report.py <release_id>
Writes reports/<release_id>_report.md and also prints it to stdout.
"""

import argparse
import datetime
import json
import os
import sys

import release_record
from verify_chain import check_chain

REPORTS_DIR = os.path.join(release_record.REPO_DIR, "reports")


def _load_record(release_id):
    path = os.path.join(release_record.RELEASES_DIR, f"{release_id}.json")
    if not os.path.exists(path):
        sys.exit(f"No release record found for '{release_id}' at {path}")
    with open(path) as f:
        return json.load(f)


def _verdict_section(verification):
    if verification.get("passed"):
        return (
            "**PASSED.** The observed runtime behavior matched what was expected "
            "for this workflow -- no violations were found."
        )
    violations = "\n".join(f"- {v}" for v in verification.get("violations", []))
    return f"**FAILED.** The observed runtime behavior did not match what was expected:\n\n{violations}"


def _integrity_section(release_id, chain_ok, problems, records):
    match = next(
        ((seq, record) for seq, (_, record) in enumerate(records) if record["release_id"] == release_id),
        None,
    )
    if match is None:
        return (
            "This record predates hash-chaining (added 2026-07-30) and carries no "
            "cryptographic integrity proof -- its authenticity rests on ordinary "
            "filesystem/git trust only."
        )

    sequence, record = match
    total = len(records)
    lines = [
        f"This record is entry **{sequence + 1} of {total}** in Guardian's release ledger "
        f"(`releases/` in the `aiops-guardian` git repository).",
        "",
        f"- This record's fingerprint (SHA-256): `{record['chain']['record_hash']}`",
        f"- Links back to the previous entry's fingerprint: `{record['chain']['previous_hash']}`",
        "",
    ]
    if chain_ok:
        lines.append(
            f"**Chain integrity: VERIFIED.** All {total} entries in the ledger were independently "
            f"re-hashed at report-generation time and confirmed to match their recorded fingerprints, "
            f"and each entry's link to the one before it holds. This record has not been altered "
            f"since it was originally written."
        )
    else:
        lines.append(
            f"**Chain integrity: FAILED.** {len(problems)} problem(s) were found while re-verifying "
            f"the ledger just now -- treat this record's authenticity as unconfirmed until resolved:"
        )
        lines.extend(f"- {p}" for p in problems)
    return "\n".join(lines)


def render_report(release_id):
    record = _load_record(release_id)
    chain_ok, problems, records = check_chain()

    bp = record["build_provenance"]
    dep = record["deployment"]

    files_changed = "\n".join(bp["files_changed"]) if bp["files_changed"] else "(no prior commit to diff against)"
    trace_line = dep["trace_url"] or "(no execution trace recorded)"

    return f"""# Guardian Release Evidence Report

**Release:** {record['release_id']}
**Recorded:** {record['timestamp']}
**Report generated:** {datetime.datetime.utcnow().isoformat()}Z

## 1. What was requested

{record['objective']}

**Requested/executed by:** {record['agent']}
**Approval:** {record['approval']}

## 2. What changed in code (build provenance)

- Commit: `{bp['commit']}`
- Commit message: {bp['commit_subject']}
- Author: {bp['commit_author']}
- Date: {bp['commit_date']}
- Branch: `{bp['branch']}`

Files changed:
```
{files_changed}
```

## 3. What ran (deployment)

- Workflow: `{dep['workflow']}`
- Full execution trace: {trace_line}

## 4. Whether it behaved as expected (runtime verification)

{_verdict_section(record['runtime_behavioral_attestation'])}

## 5. Chain of custody

{_integrity_section(release_id, chain_ok, problems, records)}

---
*Generated by `release_report.py` directly from Guardian's own release ledger -- this document is a
rendering of that data, not a separately hand-written account.*
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Render a release record as a Markdown evidence report.")
    parser.add_argument("release_id")
    parser.add_argument("--out", help="Write to this path instead of reports/<release_id>_report.md")
    args = parser.parse_args()

    report = render_report(args.release_id)

    os.makedirs(REPORTS_DIR, exist_ok=True)
    out_path = args.out or os.path.join(REPORTS_DIR, f"{args.release_id}_report.md")
    with open(out_path, "w") as f:
        f.write(report)

    print(report)
    print(f"\n[INFO] Report written to {out_path}", file=sys.stderr)
